// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY6jY0232aeVHDe4BQiHwhIhFRQrikGR0',
    appId: '1:546287003722:web:3fa864ce29d5041611deb3',
    messagingSenderId: '546287003722',
    projectId: 'daily-challenge-4cb70',
    authDomain: 'daily-challenge-4cb70.firebaseapp.com',
    storageBucket: 'daily-challenge-4cb70.appspot.com',
    measurementId: 'G-XY8XK9GVCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADZrV0B9gGvQrYfb1HBhNmgycjhzN69zw',
    appId: '1:546287003722:android:ec352c22c67e6a6811deb3',
    messagingSenderId: '546287003722',
    projectId: 'daily-challenge-4cb70',
    storageBucket: 'daily-challenge-4cb70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe8ypnM0iUJjCVMDUQUxp3GTo91kvd7og',
    appId: '1:546287003722:ios:25888c06b892e7cc11deb3',
    messagingSenderId: '546287003722',
    projectId: 'daily-challenge-4cb70',
    storageBucket: 'daily-challenge-4cb70.appspot.com',
    iosClientId: '546287003722-vgboegct6143l3t3ud3v7b1o58shq9i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe8ypnM0iUJjCVMDUQUxp3GTo91kvd7og',
    appId: '1:546287003722:ios:25888c06b892e7cc11deb3',
    messagingSenderId: '546287003722',
    projectId: 'daily-challenge-4cb70',
    storageBucket: 'daily-challenge-4cb70.appspot.com',
    iosClientId: '546287003722-vgboegct6143l3t3ud3v7b1o58shq9i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyChallenge',
  );
}
